In [187]:
import datetime  # For datetime objects
import pandas as pd  # For data manipulation

import yfinance as yf # for finance data

# visualization
%matplotlib inline
import matplotlib.pyplot as plt
from IPython.display import display

import backtrader as bt

https://github.com/teddykoker/survivorship-free-spy

In [188]:
constituents = pd.read_csv('constituents.csv', parse_dates=True)
constituents.head(2)

,2019-04-29,"['MSFT', 'AAPL', 'AMZN', 'FB', 'BRKB', 'GOOG', 'GOOGL', 'JPM', 'JNJ', 'XOM', 'V', 'BAC', 'PG', 'CSCO', 'DIS', 'VZ', 'INTC', 'HD', 'UNH', 'T', 'CVX', 'MA', 'PFE', 'BA', 'MRK', 'WFC', 'CMCSA', 'KO', 'PEP', 'C', 'NFLX', 'MCD', 'WMT', 'ORCL', 'ADBE', 'ABT', 'PM', 'PYPL', 'UNP', 'CRM', 'HON', 'AVGO', 'IBM', 'ABBV', 'MDT', 'ACN', 'UTX', 'AMGN', 'NKE', 'TMO', 'TXN', 'MMM', 'NVDA', 'COST', 'QCOM', 'LLY', 'MO', 'LIN', 'SBUX', 'NEE', 'LOW', 'DWDP', 'AMT', 'GE', 'BKNG', 'GILD', 'DHR', 'LMT', 'AXP', 'CAT', 'USB', 'BMY', 'MDLZ', 'UPS', 'COP', 'ADP', 'GS', 'CVS', 'ANTM', 'TJX', 'CELG', 'CB', 'DUK', 'CHTR', 'INTU', 'BDX', 'CME', 'MS', 'PNC', 'CL', 'CSX', 'D', 'CI', 'SLB', 'BLK', 'ISRG', 'SYK', 'EOG', 'XTSLA', 'SPGI', 'SCHW', 'SPG', 'NSC', 'SO', 'DE', 'GM', 'CCI', 'BSX', 'RTN', 'GD', 'EXC', 'NOC', 'ZTS', 'PLD', 'MU', 'MMC', 'ITW', 'ECL', 'ICE', 'ILMN', 'AGN', 'PGR', 'BIIB', 'OXY', 'FDX', 'APD', 'VRTX', 'MET', 'EMR', 'BK', 'COF', 'PRU', 'KMB', 'WBA', 'AON', 'AMAT', 'ADI', 'DOW', 'CTSH', 'AEP', 'WM', 'MPC', 'AIG', 'TGT', 'F', 'PSX', 'BBT', 'ADSK', 'KMI', 'MAR', 'EL', 'EQIX', 'VLO', 'TRV', 'AFL', 'ROP', 'ATVI', 'SHW', 'APC', 'ROST', 'EW', 'BAX', 'FIS', 'ETN', 'DAL', 'STZ', 'HUM', 'SRE', 'WMB', 'JCI', 'HCA', 'FISV', 'EBAY', 'DG', 'SYY', 'PSA', 'ALL', 'RHT', 'MCO', 'YUM', 'TEL', 'LRCX', 'VFC', 'GIS', 'ALXN', 'HPQ', 'PEG', 'XLNX', 'ORLY', 'APH', 'IR', 'STI', 'TWTR', 'XEL', 'EA', 'OKE', 'WELL', 'EQR', 'PXD', 'PPG', 'AVB', 'LYB', 'ED', 'REGN', 'DFS', 'LUV', 'PAYX', 'GLW', 'DLTR', 'STT', 'HLT', 'AZO', 'FTV', 'HAL', 'TROW', 'NEM', 'ZBH', 'PCAR', 'A', 'AMD', 'DLR', 'WEC', 'ADM', 'MSI', 'PH', 'CMI', 'MTB', 'MCHP', 'TDG', 'CXO', 'WLTW', 'ALGN', 'GPN', 'MNST', 'VRSK', 'MCK', 'SBAC', 'DTE', 'ES', 'SYF', 'SWK', 'FLT', 'APTV', 'USD', 'IQV', 'FITB', 'PPL', 'TSN', 'CCL', 'HPE', 'CNC', 'ROK', 'VTR', 'NTRS', 'CERN', 'O', 'RCL', 'BXP', 'KLAC', 'FE', 'KHC', 'VRSN', 'INFO', 'EIX', 'KR', 'UAL', 'CLX', 'AMP', 'FAST', 'AME', 'WY', 'BLL', 'IDXX', 'ULTA', 'HRS', 'AWK', 'CDNS', 'MSCI', 'MKC', 'HIG', 'IP', 'CTAS', 'MTD', 'ESS', 'FCX', 'ETR', 'CBS', 'OMC', 'NTAP', 'CHD', 'SNPS', 'KEY', 'DXC', 'AEE', 'FRC', 'RSG', 'NUE', 'BBY', 'HSY', 'LLL', 'CFG', 'FANG', 'ANET', 'TSS', 'VMC', 'KEYS', 'CMG', 'HES', 'ANSS', 'MXIM', 'CBRE', 'ARE', 'RF', 'SYMC', 'CMS', 'CNP', 'EFX', 'AJG', 'WAT', 'LH', 'XYL', 'EXPE', 'SWKS', 'K', 'GPC', 'DHI', 'LEN', 'RMD', 'PFG', 'WDC', 'DRI', 'CAG', 'MGM', 'EVRG', 'CINF', 'HBAN', 'WYNN', 'DVN', 'HCP', 'HST', 'CAH', 'MYL', 'DOV', 'L', 'COO', 'IT', 'IFF', 'MRO', 'FOXA', 'SJM', 'CE', 'LNC', 'BR', 'AAL', 'FTNT', 'EXPD', 'MLM', 'CPRT', 'NBL', 'INCY', 'BHGE', 'SIVB', 'EXR', 'WCG', 'TFX', 'KMX', 'AKAM', 'DGX', 'ETFC', 'GWW', 'TXT', 'TSCO', 'CTXS', 'APA', 'ABMD', 'NCLH', 'KSU', 'CMA', 'VAR', 'HOLX', 'UDR', 'MAA', 'VNO', 'KSS', 'AAP', 'TAP', 'HAS', 'TIF', 'ATO', 'STX', 'MAS', 'ABC', 'NRG', 'AES', 'RJF', 'JKHY', 'EMN', 'XRAY', 'CBOE', 'URI', 'CHRW', 'CTL', 'TTWO', 'REG', 'LNT', 'DRE', 'COG', 'UHS', 'FTI', 'NOV', 'NDAQ', 'HRL', 'FMC', 'GRMN', 'DISCK', 'PKI', 'PNW', 'WAB', 'VIAB', 'NI', 'BEN', 'FRT', 'CF', 'LW', 'PVH', 'HSIC', 'JNPR', 'FFIV', 'WRK', 'SNA', 'PKG', 'LKQ', 'RE', 'MOS', 'AVY', 'TPR', 'HII', 'ALLE', 'IPG', 'ZION', 'IRM', 'QRVO', 'JEC', 'NLSN', 'TMK', 'BFB', 'WHR', 'IVZ', 'BWA', 'WU', 'JBHT', 'ARNC', 'DISH', 'MHK', 'AOS', 'ALB', 'UNM', 'PHM', 'HFC', 'ALK', 'KIM', 'M', 'AIV', 'RHI', 'FBHS', 'SEE', 'SLG', 'CPB', 'DVA', 'ADS', 'FLIR', 'XEC', 'RL', 'PBCT', 'CPRI', 'HBI', 'XRX', 'FLS', 'FL', 'HP', 'FOX', 'PRGO', 'IPGP', 'AMG', 'PNR', 'LB', 'AIZ', 'HOG', 'ROL', 'PWR', 'GPS', 'FLR', 'NWL', 'HRB', 'LEG', 'TRIP', 'JEF', 'DISCA', 'COTY', 'NWSA', 'JWN', 'MAT', 'MAC', 'UAA', 'UA', 'NKTR', 'UBFUT', 'NWS', 'ESM9']"
0,2019-03-29,"['MSFT', 'AAPL', 'AMZN', 'FB', 'BRKB', 'JNJ', ..."
1,2019-02-28,"['MSFT', 'AAPL', 'AMZN', 'BRKB', 'FB', 'JNJ', ..."

In [189]:
constituents.columns = ['date', 'tickers']
constituents

           date                                            tickers
0    2019-03-29  ['MSFT', 'AAPL', 'AMZN', 'FB', 'BRKB', 'JNJ', ...
1    2019-02-28  ['MSFT', 'AAPL', 'AMZN', 'BRKB', 'FB', 'JNJ', ...
2    2019-01-31  ['MSFT', 'AAPL', 'AMZN', 'FB', 'BRKB', 'JNJ', ...
3    2018-12-31  ['MSFT', 'AAPL', 'AMZN', 'BRKB', 'JNJ', 'JPM',...
4    2018-11-30  ['MSFT', 'AAPL', 'AMZN', 'BRKB', 'JNJ', 'JPM',...
..          ...                                                ...
146  2007-01-31  ['PMCS', 'PGL', 'SANM', 'ADCT', 'GAS.2', 'DDS'...
147  2006-12-29  ['PMCS', 'ADCT', 'PGL', 'SANM', 'PMTC', 'NOVL'...
148  2006-11-30  ['PMCS', 'ADCT', 'PGL', 'NAV', 'SANM', 'MDP', ...
149  2006-10-31  ['PMCS', 'PGL', 'ADCT', 'NAV', 'DDS', 'CIEN', ...
150  2006-09-29  ['PMCS', 'ANDW', 'PGL', 'NAV', 'ADCT', 'HPC', ...

[151 rows x 2 columns]

In [190]:
row = constituents[constituents['date'] >= '2010'].iloc[-1]
start_date = row.date
tickers = row.tickers

In [191]:
sp_2010_tickers

['XOM',
 'MSFT',
 'PG',
 'JNJ',
 'AAPL',
 'GEC',
 'IBM',
 'JPM',
 'BAC',
 'PFE',
 'T',
 'WFC',
 'CVX',
 'CSCO',
 'GOOGL',
 'KO',
 'MRK',
 'WMT',
 'HPQ',
 'INCO',
 'PEP',
 'ORCL',
 'PM',
 'VZ',
 'ABT',
 'GS',
 'SLBA',
 'COP',
 'MCD',
 'QCI',
 '0R01',
 'OXY',
 'UTX',
 'AMGN',
 'UPS',
 'MMM',
 'DIS',
 'USB',
 'HD',
 'MDT',
 'CVS',
 'CMCSA',
 'AEC1',
 'BA',
 'GILD',
 'BMY',
 'AMZN',
 'MON',
 'MO',
 'KFT',
 'CL',
 'TGT',
 'UNH',
 'VISA',
 'MS',
 'F',
 'WAG',
 'LLY',
 'BK',
 'BAX',
 'EMC',
 'APA',
 'CAT',
 'TWX',
 'LOW',
 'AAZ',
 'EMR',
 'DOW',
 'UNP',
 'EXC',
 'DVN',
 'ALD',
 'DD',
 'MHS',
 'ANTM',
 'DTV',
 'MWZ',
 'FCX',
 'NCRA',
 'TXN',
 'GLW',
 'PA9',
 'HAL',
 'BNI',
 'CELG',
 'EBAY',
 'XTO',
 'GD',
 'SO',
 'PNC',
 'COST',
 'NKE',
 'KMB',
 'FDX',
 'MA',
 'LOM',
 'GIS',
 'PRU',
 'PX',
 'ESRX',
 'EOG',
 '8686',
 'D',
 'DELL',
 'DUK',
 'STT',
 'DE',
 'MRO',
 'NEM',
 'ADP',
 'SPG',
 'NEE',
 'RTN1',
 'ADM',
 'BBT',
 'MX4A',
 'TMO',
 'JCI',
 'DHR',
 'AABA',
 'BDX',
 'NTH',
 'VIAB',
 'AG4',
 'SWG',
 'NSC',
 'BLKFDS',
 'NOV',
 'CB',
 'AMT',
 'SPLS',
 'ADBE',
 'HES',
 'CSX',
 'ITW',
 'COF',
 'SYY',
 'AEP',
 'AMAT',
 'SBUX',
 'APD',
 'ALL',
 'CHK',
 'YUM',
 'TJX',
 'MCK',
 'WM',
 'PCG',
 'BIIB',
 'PEG',
 'KSS',
 'T3W1',
 'SWN',
 'PCP',
 'BEN',
 'SYK',
 'CCL',
 'ETR',
 'GENZ',
 'MOT',
 'BHI',
 'KR',
 'K',
 'HNZ',
 'SE',
 'SYMC',
 'FE',
 'PCAR',
 'JNPR',
 'BSX',
 'AET',
 'LTR',
 'AVP',
 'CTSH',
 'NUE',
 'WU',
 'NBL',
 'TROW',
 'STJ',
 'ISRG',
 'BBY',
 'SRE',
 'AA',
 'ED',
 'NTRS',
 'LO',
 'WMB',
 'STI',
 'CAH',
 'ZBH',
 'BRCM',
 'MMC',
 'BTU',
 'PGR',
 'MHFI',
 'COH',
 'PPL',
 'OMC',
 'PGN',
 'EIX',
 'PSA',
 'AON',
 'ECL',
 'VLO',
 'BBBY',
 'ETN',
 'VNO',
 'CTL',
 'CAG',
 'IP',
 'FITB',
 'NTAP',
 'PPG',
 'MUR',
 'AMP',
 'S',
 'LLL',
 'A',
 'CHRW',
 'XEL',
 'INTU',
 'PAYX',
 'MJN',
 'CI',
 'CAM',
 'HIG',
 'SWY',
 'CMI',
 'GPS',
 'BXP',
 'RAI',
 'PH',
 'FRX',
 'LIFE',
 'EQR',
 'ITT',
 'CBS',
 'CA',
 'RSG',
 'DGX',
 'PCLN',
 'WDC',
 'NVDA',
 'SLE',
 'CNX',
 'WY',
 'AES',
 'LUV',
 'COL',
 'HCP',
 'IVZ',
 'CLX',
 'HUM',
 'HSP',
 'FLR',
 'BCR',
 'DOV',
 'ADI',
 'ABC',
 'CSC',
 'APOL',
 'FIS',
 'GR',
 'CTXS',
 'XRX',
 'LH',
 'RN7',
 'SII',
 'DC7',
 'LNC',
 'MU',
 'PFG',
 'RRC',
 'STR',
 'EXPD',
 'HRB',
 'SJM',
 'MAT',
 'EP',
 'BMC',
 'DPS',
 'ICE',
 'CRM',
 'DTE',
 'FISV',
 'ROK',
 'APH',
 'GNW',
 'M',
 'HST',
 'MAR',
 'TAP',
 'VTR',
 'XLNX',
 'FTI',
 'CEG',
 'UUM',
 'CCE',
 'VFC',
 'USX1',
 'DO',
 'NBR',
 'KEY',
 'ALTR',
 'CPB',
 'HCBK',
 'GWW',
 'VAR',
 'QWST',
 'FO',
 'AVB',
 'HOT',
 'EL',
 'DVA',
 'MTZ',
 'NYX',
 'BJS',
 'HSY',
 'AEE',
 'SHW',
 'GPC',
 'ACS',
 'SCN',
 'MFE',
 'PCL',
 'JCP',
 'SIAL',
 'LLTC',
 'SNDK',
 'EQT',
 'ROST',
 'WEC',
 'XL',
 'JWN',
 'HRS',
 'BFB',
 'PBCT',
 'LDOS',
 'WHR',
 'MYL',
 'VMC',
 'FSLR',
 'FAST',
 'ADSK',
 'IGT',
 'CNP',
 'MCO',
 'WAT',
 'PBG',
 'HOG',
 'EA',
 'TXT',
 'HCN',
 'CLF',
 'CMA',
 'ORLY',
 'DRI',
 'RHT',
 'XRAY',
 'LTD',
 'PXD',
 'KIM',
 'TIF',
 'FLS',
 'SLM',
 'MAS',
 'KLAC',
 'TDC',
 'BLL',
 'CEPH',
 'MKC',
 'MCHP',
 'RL',
 'JEC',
 'AZO',
 'OI',
 'CFN',
 'ROP',
 'SHLD',
 'EXPE',
 'CF',
 'WIN',
 'FLIR',
 'SRCL',
 'ES',
 'VRSN',
 'PBI',
 'CINF',
 'FDO',
 'WYNN',
 'LUK',
 'AKAM',
 'TSN',
 'AMD',
 'LM',
 'IRM',
 'MWV',
 'SWK',
 'EMN',
 'DNB',
 'WPI',
 'RRD',
 'RHI',
 'EFX',
 'PLL',
 'ATI',
 'COG',
 'RX',
 'SCG',
 'NI',
 'BDK',
 'MIL',
 'WFM',
 'PWR',
 'SNI',
 'TGNA',
 'HAS',
 'DV',
 'NWL',
 'WYN',
 'TMK',
 'FMC',
 'AVY',
 'AIZ',
 'POM',
 'PNW',
 'MI',
 'AYE',
 'CMS',
 'ARG',
 'HBAN',
 'CVH',
 'DNR',
 'TE',
 'PHM',
 'CBG',
 'CTAS',
 'MEE',
 'AIG',
 'LSI',
 'GME',
 'DHI',
 'GT',
 'STZ',
 'TEG',
 'DF',
 'SEE',
 'IFF',
 'IPG',
 'NSM2',
 'SVU',
 'NRG',
 'BMS',
 'PTV',
 'KG',
 'SUN',
 'FHN',
 'TSS',
 'WFR',
 'LEG',
 'ANF',
 'JBL',
 'MOLX',
 'HRL',
 'GHC',
 'PDCO',
 'NDAQ',
 'ZION',
 'TLAB',
 'LEN',
 'HAR',
 'RDC',
 'RSHCQ',
 'THC',
 'FTR',
 'SNA',
 'ETFC',
 'PKI',
 'BIG',
 'FII',
 'AKS',
 'JNS',
 'R',
 'NVLS',
 'LXK',
 'QLG',
 'MWW',
 'GAS2',
 'AIV',
 'TSO',
 'CPWR',
 'UNS1',
 'AN',
 'TER',
 'EKDKQ',
 'ODP',
 'NOVL',
 'NYT',
 'PCS',
 'MDP',
 'TIE']

In [192]:
import re

sp_2010_tickers = [re.sub(r'[^a-zA-Z0-9]', '', ticker) for ticker in sp_2010_tickers]

In [193]:
start_date

'2010-01-29'

In [194]:
df = yf.download(sp_2010_tickers, start=start_date)['Close']

[*********************100%***********************]  501 of 501 completed

132 Failed downloads:
['FDO', 'SIAL', 'LXK', 'BCR', 'PCS', 'ARG', 'PGN', 'CFN', 'DPS', 'CBG', 'SWY', 'HSP', 'RSHCQ', 'MWV', 'NYX', 'SPLS', 'RAI', 'WFM', 'SLBA', 'COH', 'LLTC', 'JNS', 'BJS', 'LUK', 'CEPH', 'MHFI', 'KFT', 'LO', 'TSO', 'WYN', 'GENZ', 'WAG', 'NOVL', 'PCLN', 'MJN', 'NVLS', 'POM', 'MOT', 'MIL', 'SNI', 'STJ', 'APOL', 'BNI', 'XTO', 'LTD', 'HCBK', 'HCN', 'MWW', 'CAM', 'BRCM']: YFPricesMissingError('possibly delisted; no price data found  (1d 2010-01-29 -> 2025-06-08)')
['RDC', 'AVP', 'USX1', 'RHT', 'T3W1', 'RN7', 'CHK', 'FRX', 'HRS', 'CTL', 'PKI', 'NSM2', 'CTXS', 'BLL', 'GEC', 'VIAB', '8686', 'UNS1', 'LLL', 'CBS', 'AKS', 'FTR', 'MYL', 'FLIR', 'DC7', 'DNR', 'FII', 'NBL', 'UTX', 'GAS2', 'SWN', 'BIG', 'BFB', 'COG', 'TSS', 'EKDKQ', 'RRD', 'DO', 'VISA', 'XL', 'AG4', 'PBCT', 'PXD', 'FISV', 'JEC', 'LIFE', 'PA9', 'ABC', 'BBBY', 'ALTR', 'AEC1', 'HCP', 'WIN', 'DF', 'RTN1', '0R01', 'LM', 'MON', 'MRO', 'JCP', 'VAR', 'AABA', 'LSI', 'ETFC', 'CELG', 'DTV', 'MX4A', 'XLNX', 'BBT', 'BLKFDS', 'GPS', 'MDP', 'TIF', 'SYMC', 'ANTM', 'TMK']: YFTzMissingError('possibly delisted; no timezone found')
['SCG', 'AET', 'TWX', 'SVU', 'HOT', 'BMS']: ValueError('Length mismatch: Expected axis has 2 elements, new values have 1 elements')

In [195]:
df

Ticker,0R01,8686,A,AA,AABA,AAPL,AAZ,ABC,ABT,ACS,...,XEL,XL,XLNX,XOM,XRAY,XRX,XTO,YUM,ZBH,ZION
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-29,NaN,NaN,17.886896,27.200359,NaN,5.772205,46.500000,NaN,18.193033,1.188,...,12.292807,NaN,NaN,35.936111,29.068953,11.103883,NaN,18.335852,48.911526,14.310552
2010-02-01,NaN,NaN,18.588850,28.546482,NaN,5.852453,45.380001,NaN,18.330492,1.197,...,12.334216,NaN,NaN,36.912182,29.112297,11.422227,NaN,18.984386,49.528141,15.027209
2010-02-02,NaN,NaN,18.824957,29.208866,NaN,5.886412,44.360001,NaN,18.708513,1.178,...,12.523519,NaN,NaN,37.347233,29.918566,11.625972,NaN,19.198782,50.631054,15.019666
2010-02-03,NaN,NaN,18.850477,28.887659,NaN,5.987695,45.889999,NaN,18.780682,1.188,...,12.375629,NaN,NaN,37.146458,29.363722,11.447696,NaN,18.941504,49.614971,14.046522
2010-02-04,NaN,NaN,18.550560,27.645636,NaN,5.771906,46.430000,NaN,18.495455,1.159,...,11.967443,NaN,NaN,36.097866,28.427408,11.014749,NaN,17.901712,48.303596,13.194073
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-06-02,NaN,NaN,111.050003,26.600000,NaN,201.699997,NaN,NaN,133.570007,NaN,...,69.730003,NaN,NaN,103.050003,15.620000,4.840000,NaN,144.630005,91.110001,46.950001
2025-06-03,NaN,NaN,112.760002,27.660000,NaN,203.270004,NaN,NaN,133.710007,NaN,...,69.330002,NaN,NaN,103.800003,15.890000,5.000000,NaN,143.970001,91.849998,48.250000
2025-06-04,NaN,NaN,114.940002,27.370001,NaN,202.820007,NaN,NaN,132.960007,NaN,...,68.500000,NaN,NaN,102.300003,16.100000,5.050000,NaN,144.009995,91.459999,47.580002
2025-06-05,NaN,NaN,113.940002,27.870001,NaN,200.630005,NaN,NaN,133.940002,NaN,...,68.570000,NaN,NaN,101.830002,15.900000,4.990000,NaN,142.880005,91.919998,47.680000
2025-06-06,NaN,NaN,115.800003,28.010000,NaN,203.919998,NaN,NaN,133.580002,NaN,...,68.510002,NaN,NaN,104.269997,15.940000,5.130000,NaN,144.830002,92.379997,49.279999

In [196]:
monthly_prices = df.resample('ME').last()
monthly_prices

Ticker,0R01,8686,A,AA,AABA,AAPL,AAZ,ABC,ABT,ACS,...,XEL,XL,XLNX,XOM,XRAY,XRX,XTO,YUM,ZBH,ZION
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-31,NaN,NaN,17.886896,27.200359,NaN,5.772205,46.50,NaN,18.193033,1.188,...,12.292807,NaN,NaN,35.936111,29.068953,11.103883,NaN,18.335852,48.911526,14.310552
2010-02-28,NaN,NaN,20.075693,28.480785,NaN,6.149687,51.00,NaN,18.653536,1.178,...,12.310555,NaN,NaN,36.490562,28.687485,11.931584,NaN,18.073227,49.788666,13.993949
2010-03-31,NaN,NaN,21.945431,30.493700,NaN,7.062732,53.00,NaN,18.103689,1.150,...,12.685821,NaN,NaN,37.602100,30.283127,12.470749,NaN,20.544088,51.412666,16.484772
2010-04-30,NaN,NaN,23.138744,28.759171,NaN,7.846846,47.82,NaN,17.729439,0.998,...,13.014936,NaN,NaN,38.045616,31.819853,13.941663,NaN,22.852837,52.897751,21.685324
2010-05-31,NaN,NaN,20.650011,24.985628,NaN,7.720318,43.68,NaN,16.481865,0.732,...,12.260971,NaN,NaN,34.172340,28.156019,11.907970,NaN,22.060905,48.572823,18.083893
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-02-28,NaN,NaN,127.648804,33.031174,NaN,241.523270,NaN,NaN,137.373657,NaN,...,71.501526,NaN,NaN,110.313988,16.380690,6.468450,NaN,155.606689,104.096977,53.571037
2025-03-31,NaN,NaN,116.732002,30.396294,NaN,221.839096,NaN,NaN,132.038361,NaN,...,70.790001,NaN,NaN,117.844627,14.940000,4.830000,NaN,156.591873,113.180000,49.427311
2025-04-30,NaN,NaN,107.599998,24.446594,NaN,212.221710,NaN,NaN,130.750000,NaN,...,70.699997,NaN,NaN,104.666008,13.900000,4.410000,NaN,149.705643,103.050003,44.579746
2025-05-31,NaN,NaN,111.919998,26.770000,NaN,200.850006,NaN,NaN,133.580002,NaN,...,70.099998,NaN,NaN,102.300003,15.980000,4.890000,NaN,143.940002,92.169998,47.360001
2025-06-30,NaN,NaN,115.800003,28.010000,NaN,203.919998,NaN,NaN,133.580002,NaN,...,68.510002,NaN,NaN,104.269997,15.940000,5.130000,NaN,144.830002,92.379997,49.279999

In [197]:
momentum = monthly_prices.pct_change(12).shift(1)
momentum = momentum.iloc[13:] # drop the first 12 months of NaN values
momentum = momentum.dropna(axis=1)
momentum # returns over the last 12 months for each month

/var/folders/v9/tn6d82cx4gd1k62yqr97qy_40000gn/T/ipykernel_60662/1900510244.py:1: FutureWarning: The default fill_method='pad' in DataFrame.pct_change is deprecated and will be removed in a future version. Either fill in any non-leading NA values prior to calling pct_change or specify 'fill_method=None' to not fill NA values.
  momentum = monthly_prices.pct_change(12).shift(1)

Ticker,A,AA,AAPL,AAZ,ABT,ACS,ADBE,ADI,ADM,ADP,...,WU,WY,WYNN,XEL,XOM,XRAY,XRX,YUM,ZBH,ZION
Date,,,,,,,,,,,,,,,,,,,,,
2011-02-28,0.492330,0.314010,0.766740,0.174409,-0.116459,-0.481481,0.023220,0.481500,0.112750,0.213103,...,0.109945,0.583377,1.040960,0.186475,0.286068,0.064607,0.239018,0.395137,0.050426,0.245281
2011-03-31,0.337572,0.278356,0.726175,0.147255,-0.082171,-0.531409,-0.004329,0.402916,0.291799,0.241332,...,0.414039,0.657139,1.099417,0.203362,0.349739,0.136230,0.167181,0.523473,0.087389,0.262086
2011-04-30,0.302123,0.251366,0.483022,0.089057,-0.035617,-0.504348,-0.062482,0.403911,0.271063,0.191078,...,0.242256,0.490381,0.820550,0.177906,0.288400,0.066907,0.110820,0.368203,0.022466,0.057628
2011-05-31,0.376448,0.277252,0.341033,0.097449,0.054689,-0.622244,-0.001488,0.383769,0.351611,0.293883,...,0.181127,0.273137,0.816690,0.169265,0.331653,0.030753,-0.058624,0.290551,0.071252,-0.147898
2011-06-30,0.541100,0.456284,0.354056,0.259158,0.139101,-0.409836,0.079489,0.447935,0.307637,0.391633,...,0.306745,0.395320,0.896757,0.262083,0.414567,0.217309,0.115256,0.378750,0.211515,-0.003285
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-02-28,0.172724,0.201251,0.286096,0.000000,0.153664,0.000000,-0.291900,0.120214,-0.045005,0.259917,...,-0.111742,-0.037551,-0.070179,0.165554,0.074547,-0.416551,-0.495248,0.027856,-0.120844,0.431485
2025-03-31,-0.062263,0.236412,0.344298,0.000000,0.186973,0.000000,-0.217249,0.219699,-0.077632,0.282601,...,-0.126236,-0.102023,-0.141299,0.420952,0.101108,-0.480379,-0.612130,0.151839,-0.153927,0.416905
2025-04-30,-0.190491,-0.087089,0.301486,0.000000,0.190861,0.000000,-0.239933,0.036540,-0.206692,0.249695,...,-0.177307,-0.162725,-0.173929,0.364394,0.057677,-0.535660,-0.702511,0.157209,-0.134841,0.187721
2025-05-31,-0.208985,-0.293987,0.253469,0.000000,0.258574,0.000000,-0.189810,-0.012236,-0.155169,0.269431,...,-0.198445,-0.118130,-0.113770,0.363167,-0.076728,-0.522205,-0.634161,0.085956,-0.135652,0.140060
2025-06-30,-0.135397,-0.387819,0.049619,0.000000,0.333378,0.000000,-0.066710,-0.072320,-0.196000,0.357704,...,-0.211871,-0.112826,-0.034910,0.309673,-0.097159,-0.411486,-0.616558,0.067907,-0.192468,0.133054

In [199]:
portfolio = pd.DataFrame(index=monthly_prices.index, columns=monthly_prices.columns)
portfolio

Ticker,0R01,8686,A,AA,AABA,AAPL,AAZ,ABC,ABT,ACS,...,XEL,XL,XLNX,XOM,XRAY,XRX,XTO,YUM,ZBH,ZION
Date,,,,,,,,,,,,,,,,,,,,,
2010-01-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2010-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2025-02-28,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-03-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-04-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-05-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2025-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
constituents['date'] = pd.to_datetime(constituents['date'])
constituents = constituents.set_index('date')

In [202]:
def get_tickers_date(df, date):
    if date >= df.index[-1]:
        ticks = df.iloc[-1].tickers
    else:
        ticks = df.loc[date:].iloc[0].tickers
    return ticks.split(',')

for date in momentum.index:
    pf_date = momentum.loc[date]
    relevant_tickets = get_tickers_date(constituents, date)
    pf_date = pf_date[pf_date.index.isin(relevant_tickets)]
    top20 = pf_date.nlargest(20)
    portfolio.loc[date, top20.index] = 1 / 20

In [205]:
portfolio.loc[date, top20]

Series([], Name: 2025-06-30 00:00:00, dtype: object)